### ISSUE TITLE
[TODO] WidgetAspect for Custom Search Results

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.horizon.2#11]
- [x] Skinshortcuts
- [x] Powermenu
- [x] Fullscreen widget setup
- [x] Multiwidget setup
- [x] Submenu pop-ups
- [x] Submenu widgets
- [x] Widget aspects
- [x] Widget sort methods
- [ ] Background images
- [ ] Global widget
- [ ] Hub links to copy home screen setup
- [ ] Alternative hub views (???)
- [ ] WidgetAspect for Custom Search Results

**Comment by Goldenfreddy0703** [comment]
Thank you

**Comment by jurialmunkey** [comment]
Added to my todo list. Not completed yet - just github says that now when the issue is closed! But will be added soon!

**Comment by Goldenfreddy0703** [comment]
Oh ok, thank you very much and love the new skin you made.

**Comment by jurialmunkey** [comment]
Should be in now! I also set up the default configuration to use better aspects (e.g. by default album/artist uses square now , and episodes uses landscape).
