### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/skin.arctic.horizon.2#7]
### Furniture
- [x] Now playing VARs for music+PVR
- [x] #203

### Player / OSD
- [ ] Better playlist selection
- [x] Option to always show stop button
- [x] #202
- [x] Visualisation preset
- [x] #296

### Home / Hubs
- [x] Widget item limits
- [x] Background images
- [ ] Global widget
- [ ] Hub links to copy home screen setup
- [ ] Alternative hub views
- [ ] Basic hubs

### Library / Views
- [x] Banner views
- [x] #297
- [x] Wall scroll
- [x] MyPrograms
- [ ] #298

### Custom Windows
- [ ] Up Next simple
- [ ] Quick Songlist (maybe in music info)

### Video Info
- [x] #204
- [x] #205
- [ ] #206
- [x] #207

### Options / Setup
- [x] #211
- [x] #210
- [x] #209
- [x] #208

### Complete
- [x] Trailers
- [x] Trailer Picture in Picture
- [x] Play Action compatible with TMDbHelper (appears to be working)
- [x] Browse action in video info
- [x] Seasons / Episodes / Collections lists for Recommendations
- [x] PVR Guide
- [x] PVR Channels
- [x] PVR Recordings
- [x] PVR Timers
- [x] PVR Search
- [x] Addon Info
- [x] Music Info
- [x] Pictures Info
- [x] PVR Info
- [x] Next Aired window
- [x] Search window
- [x] Discover window
- [x] Similar
- [x] Plotbox / Textbox to Context Style
- [x] Up Next dialogs
- [x] MyPics
- [x] Combined view loading indicators
- [x] MyMusicNav
- [x] Fullscreenvideo
- [x] Visualisation
- [x] Music seekbar
- [x] Artist slideshow
- [x] Bookmarks
- [x] Chapter viewer/selection in pop-up
- [x] Tags views
- [x] Song list view
- [x] Scrollbars
- [x] Alphabet Strip
- [x] Plotbox
- [x] Quickbar
- [x] Slider dialog for offsets
- [x] Codec details overlay
- [x] PVR record button
- [x] PVR support for channel switch
- [x] PVR osd channels and epg (put in pop-up?)
- [x] Skinshortcuts
- [x] Powermenu
- [x] Fullscreen widget setup
- [x] Multiwidget setup
- [x] Submenu pop-ups
- [x] Submenu widgets
- [x] Widget aspects
- [x] Widget aspect for search
- [x] SkinVariables setup
- [x] Wall views
- [x] List views
- [x] Info list views
- [x] Widget sort methods

**Comment by jurialmunkey** [comment]
- [ ] Test
